# Generated by Django 5.2.12 on 2026-03-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superuser', 'Superuser'), ('manager', 'Manager'), ('hr', 'HR'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
