# Generated by Django 5.2.3 on 2026-03-06 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('storage_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('bandwidth_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('database_count', models.IntegerField(default=0)),
                ('database_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ports_used', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('server_type', models.CharField(help_text='VPS, Dedicated, Cloud, etc.', max_length=100)),
                ('provider', models.CharField(help_text='e.g. Contabo, AWS, DigitalOcean', max_length=150)),
                ('portal_url', models.URLField(blank=True, null=True)),
                ('storage', models.CharField(help_text='e.g. 400GB NVMe', max_length=100)),
                ('ram', models.CharField(help_text='e.g. 16GB', max_length=100)),
                ('bandwidth', models.CharField(help_text='e.g. 32TB Outgoing', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Data Center Location', max_length=150, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_details', models.TextField(blank=True, help_text='IP, Port, Username, special instructions', null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=50)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registrar', models.CharField(max_length=150)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('nameservers', models.TextField(blank=True, null=True)),
                ('dns_records', models.TextField(blank=True, null=True)),
                ('whois_info', models.TextField(blank=True, null=True)),
                ('transfer_lock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='infrastructure.hostedproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(upload_to='server_invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='infrastructure.server')),
            ],
        ),
        migrations.AddField(
            model_name='hostedproject',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='infrastructure.server'),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=255)),
                ('login_url', models.URLField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recovery_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('security_questions', models.TextField(blank=True, help_text='List of security questions and answers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccountAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='Viewed Password', max_length=255)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='infrastructure.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(default="Let's Encrypt", max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('domains_covered', models.TextField(blank=True, help_text='e.g. example.com, *.example.com', null=True)),
                ('renewal_process', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Auto', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='infrastructure.domain')),
            ],
        ),
    ]
