# Generated by Django 5.2.3 on 2026-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Prompt for making documentation', max_length=255)),
                ('content', models.TextField(help_text='The actual prompt text')),
                ('category', models.CharField(blank=True, help_text='e.g. Coding, Marketing, Writing', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional context or instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
