# Generated by Django 5.2.12 on 2026-04-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_labels', to='infrastructure.server')),
            ],
            options={
                'ordering': ['port'],
                'unique_together': {('server', 'port')},
            },
        ),
    ]
