# Generated by Django 5.2.12 on 2026-03-06 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Annual', 'Annual'), ('ProductLaunch', 'Product Launch'), ('MarketExpansion', 'Market Expansion'), ('Custom', 'Custom')], default='Annual', max_length=50)),
                ('category', models.CharField(choices=[('Marketing', 'Marketing'), ('Product', 'Product/Service Development'), ('MarketExpansion', 'Market Expansion'), ('Risk', 'Risk Management'), ('Resource', 'Resource Planning'), ('General', 'General')], default='General', max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('OnHold', 'On Hold')], default='Planning', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('board_state', models.JSONField(blank=True, default=dict, help_text='Stores tldraw canvas JSON state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('campaign', 'Campaign'), ('content', 'Content'), ('social', 'Social Media'), ('ad_budget', 'Advertising Budget'), ('lead_target', 'Lead Generation Target'), ('service', 'New Service/Product'), ('feature', 'Feature'), ('tech', 'Technology Upgrade'), ('training', 'Training'), ('industry', 'Target Industry'), ('geo', 'Geographic Expansion'), ('partnership', 'Partnership'), ('competitor', 'Competitor Analysis'), ('risk', 'Identified Risk'), ('mitigation', 'Mitigation Strategy'), ('contingency', 'Contingency Plan'), ('hire', 'Hire'), ('equipment', 'Equipment/Software'), ('office', 'Office Expansion'), ('budget', 'Budget Allocation'), ('goal', 'Goal'), ('milestone', 'Milestone'), ('other', 'Other')], default='goal', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Done', 'Done'), ('Blocked', 'Blocked')], default='Pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('value', models.CharField(blank=True, help_text='Numeric target, budget amount, etc.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.plan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
