# Generated by Django 5.2.3 on 2026-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Base64 encoded image', null=True),
        ),
    ]
