# Generated by Django 5.2.3 on 2026-03-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('Contract', 'Contract'), ('Proposal', 'Proposal'), ('Invoice', 'Invoice'), ('Quote', 'Quotation'), ('NDA', 'NDA'), ('SLA', 'SLA'), ('Other', 'Other')], default='Contract', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('file', models.FileField(upload_to='templates/documents/')),
                ('variables', models.JSONField(blank=True, default=list, help_text="List of expected variables in the template e.g. ['client_name', 'project_name']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Viewed', 'Viewed'), ('Signed', 'Signed'), ('Expired', 'Expired')], default='Draft', max_length=50)),
                ('file_word', models.FileField(blank=True, null=True, upload_to='documents/word/')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='documents/pdf/')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='documents/signed/')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='crm.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='projects.project')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='contracts_docs.documenttemplate')),
            ],
        ),
    ]
